package com.example.samojlov_av_homework_module_15_number_9_1_koala.models

import com.example.samojlov_av_homework_module_15_number_9_1_koala.R

data class ProductShop(
    val name: String,
    val price: Double,
    val image: Int,
    val currency: String,
    var count: Int,
) {
    companion object {
        val productsList = mutableListOf(
            ProductShop("Картофель", 936.47, R.drawable.potato, "руб.", 0),
            ProductShop("Морковь", 1000.15, R.drawable.carrot, "руб.", 0),
            ProductShop("Лук", 1121.26, R.drawable.onion, "руб.", 0),
            ProductShop("Чеснок", 2012.39, R.drawable.garlic, "руб.", 0),
            ProductShop("Петрушка", 707.02, R.drawable.punch, "руб.", 0),
            ProductShop("Укроп", 1187.46, R.drawable.dill, "руб.", 0),
            ProductShop("Яблоки", 1152.26, R.drawable.apples, "руб.", 0),
            ProductShop("Бананы", 1038.07, R.drawable.bananas, "руб.", 0),
            ProductShop("Лимон", 488.3, R.drawable.lemon, "руб.", 0),
            ProductShop("Масло сливочное", 2640.84, R.drawable.butter, "руб.", 0),
            ProductShop("Кефир", 1651.82, R.drawable.kefir, "руб.", 0),
            ProductShop("Молоко ", 2747.84, R.drawable.milk, "руб.", 0),
            ProductShop("Сметана", 1627.49, R.drawable.sour_cream, "руб.", 0),
            ProductShop("Творог", 676.46, R.drawable.cottage_cheese, "руб.", 0),
            ProductShop("Сыр", 920.82, R.drawable.cheese, "руб.", 0),
            ProductShop("Горчица", 1038.25, R.drawable.mustard, "руб.", 0),
            ProductShop("Малиновое варенье", 1676.15, R.drawable.raspberry_jam, "руб.", 0),
            ProductShop("Томатная паста", 302.74, R.drawable.tomato_paste, "руб.", 0),
            ProductShop("Рыбная консерва", 1714.06, R.drawable.fish_preserves, "руб.", 0),
            ProductShop("Консервированный горошек", 533.68, R.drawable.canned_peas, "руб.", 0),
            ProductShop("Консервированная кукуруза", 1490.37, R.drawable.canned_corn, "руб.", 0),
            ProductShop("Детское питание", 700.6, R.drawable.baby_food, "руб.", 0),
            ProductShop("Сгущенное молоко", 1419.32, R.drawable.condensed_milk, "руб.", 0),
            ProductShop("Мед", 2490.49, R.drawable.honey, "руб.", 0),
            ProductShop("Яйца", 1728.89, R.drawable.eggs, "руб.", 0),
            ProductShop("Масло растительное", 1342.61, R.drawable.vegetable_oil, "руб.", 0),
            ProductShop("Соевый соус", 301.96, R.drawable.soy_sauce, "руб.", 0),
            ProductShop("Уксус ", 475.1, R.drawable.vinegar, "руб.", 0),
            ProductShop("Сливки взбитые", 2126.67, R.drawable.whipped_cream, "руб.", 0),
            ProductShop("Кошачий корм", 1828.54, R.drawable.cat_food, "руб.", 0),
            ProductShop("Фрикадельки ", 2913.86, R.drawable.meatballs, "руб.", 0),
            ProductShop("Котлеты ", 1852.88, R.drawable.chops, "руб.", 0),
            ProductShop("Суповой набор куриный", 2492.82, R.drawable.chicken_soup_set, "руб.", 0),
            ProductShop("Суповой набор мясной", 1570.63, R.drawable.meat_soup_set, "руб.", 0),
            ProductShop("Курица бедро", 1416.31, R.drawable.chicken_thigh, "руб.", 0),
            ProductShop("Курица филе", 1557.43, R.drawable.chicken_fillet, "руб.", 0),
            ProductShop("Свинина ", 1978.83, R.drawable.pork, "руб.", 0),
            ProductShop("Сало", 2864.08, R.drawable.lard, "руб.", 0),
            ProductShop("Стручковая фасоль", 699.65, R.drawable.green_beans, "руб.", 0),
            ProductShop("Маргарин", 919.59, R.drawable.margarine, "руб.", 0),
            ProductShop("Смородина", 1983.13, R.drawable.currant, "руб.", 0),
            ProductShop("Клубника", 2392.63, R.drawable.strawberry, "руб.", 0),
            ProductShop("Клюква ", 857.58, R.drawable.cranberry, "руб.", 0),
            ProductShop("Грибы", 959.21, R.drawable.mushrooms, "руб.", 0),
            ProductShop("Шпинат", 1400.95, R.drawable.spinach, "руб.", 0),
            ProductShop("Рыба", 553.14, R.drawable.fish, "руб.", 0),
            ProductShop("Крабовые палочки", 1924.92, R.drawable.crab_sticks, "руб.", 0),
            ProductShop("Колбаса вареная", 2138.12, R.drawable.boiled_sausage, "руб.", 0),
            ProductShop("Колбаса капченая", 602.65, R.drawable.captcha_sausage, "руб.", 0),
            ProductShop("Салями", 2987.98, R.drawable.salami, "руб.", 0),
            ProductShop("Сосиски", 321.74, R.drawable.sausages_thin, "руб.", 0),
            ProductShop("Шпикачки", 2346.14, R.drawable.shpikachki, "руб.", 0),
            ProductShop("Сардельки", 1673.53, R.drawable.sausages, "руб.", 0),
            ProductShop("Чипсы", 468.86, R.drawable.chips, "руб.", 0),
            ProductShop("Хлеб", 2740.55, R.drawable.bread, "руб.", 0),
            ProductShop("Батон", 1649.76, R.drawable.loaf, "руб.", 0),
            ProductShop("Помидоры", 2953.99, R.drawable.tomatoes, "руб.", 0),
            ProductShop("Огурцы", 2163.01, R.drawable.cucumbers, "руб.", 0),
            ProductShop("Капуста", 1993.59, R.drawable.cabbage, "руб.", 0),
            ProductShop("Помидоры чери", 2957.25, R.drawable.cherry_tomatoes, "руб.", 0),
            ProductShop("Груши", 913.98, R.drawable.pears, "руб.", 0),
            ProductShop("Салат", 1899.86, R.drawable.salad, "руб.", 0),
            ProductShop("Говядина на кости", 821.43, R.drawable.beef_on_the_bone, "руб.", 0),
            ProductShop("Говядина вырезка", 1612.09, R.drawable.beef_tenderloin, "руб.", 0),
            ProductShop("Тортик", 2812.81, R.drawable.cake, "руб.", 0),
            ProductShop("Сладкий рулет", 1303.67, R.drawable.sweet_roll, "руб.", 0),
            ProductShop("Вафли", 2097.89, R.drawable.waffles, "руб.", 0),
            ProductShop("Печенье", 921.1, R.drawable.cookie, "руб.", 0),
            ProductShop("Конфеты ассорти", 2371.8, R.drawable.assorted_candies, "руб.", 0),
            ProductShop("Мороженое", 256.45, R.drawable.ice_cream, "руб.", 0),
        )
    }
}